version: '3.9'

services:
  web:
    build: .
    container_name: iron_board_web
    entrypoint: [ "./entrypoint.sh" ]         # <-- Use entrypoint
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  #   depends_on:
  #     - db

  # db:
  #   image: postgres:14
  #   container_name: iron_board_db
  #   environment:
  #     POSTGRES_DB: codespikedb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
